yatube/about/urls.py
from django.urls import path
from . import views


app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path("create/", views.post_create, name="post_create"),
]

yatube/users/urls.py
from . import views

# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path

app_name = "users"

urlpatterns = [
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(template_name="users/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            # template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_confirm/done/",
        PasswordResetCompleteView.as_view(
            # template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts"
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts"
    )

    class Meta:
        ordering = ['-pub_date']
    
    def __str__(self) -> str: 
        return self.text 

yatube/users/models.py
from django.db import models

yatube/posts/forms.py
# from dataclasses import fields
# from msilib import datasizemask
from django import forms
from .models import Post

MIN_POST_LEN = 30


class PostForm(forms.ModelForm):
    """Форма добавления поста."""

    class Meta:
        model = Post
        fields = ("text", "group")

    def clean_text(self):
        data = self.cleaned_data["text"]

        if len(data) < MIN_POST_LEN:
            raise forms.ValidationError(
                f"Длинна поста должна быть не менее {MIN_POST_LEN} символов!"
            )

        return data

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    """Cобственный класс для формы регистрации."""

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = "about/author.html"


class AboutTechView(TemplateView):
    template_name = "about/tech.html"

yatube/posts/views.py
from multiprocessing import context
from tempfile import tempdir
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .models import Group, Post, User
from .forms import PostForm

POST_PER_PAGE = 10


def index(request):
    """В переменную page_obj будет сохранена выборка из POST_PER_PAGE объектов модели Post,
    отсортированных по полю pub_date по убыванию,
    с учетом номера страницы переданного в GET.
    """

    post_list = Post.objects.all().order_by("-pub_date")
    paginator = Paginator(post_list, POST_PER_PAGE)

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    """Страница список постов."""
    group = get_object_or_404(Group, slug=slug)

    post_list = group.posts.all()
    paginator = Paginator(post_list, POST_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    template = "posts/group_list.html"
    context = {
        "group": group,
        "page_obj": page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    """Список постов пользователя, общее количество постов, инофрмация о пользователе."""

    author = get_object_or_404(User, username=username)

    post_list = author.posts.all()

    paginator = Paginator(post_list, POST_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    template = "posts/profile.html"
    context = {
        "page_obj": page_obj,
        "author": author,
    }

    return render(request, template, context)


def post_detail(request, post_id):
    """Страница поста и количество постов пользователя."""

    post = get_object_or_404(Post, pk=post_id)

    template = "posts/post_detail.html"
    context = {"post": post}

    return render(request, template, context)


def post_create(request):
    """Добавления поста."""

    template = "posts/create_post.html"

    if request.method == "POST":
        form = PostForm(request.POST or None)

        if form.is_valid():
            text = form.cleaned_data["text"]
            group = form.cleaned_data["group"]

            instance = form.save(commit=False)
            instance.author_id = request.user.id
            instance.save()

            user_name = request.user.username

            return redirect("posts:profile", user_name)

        return render(request, template, {"form": form})

    form = PostForm()

    return render(request, template, {"form": form})


def post_edit(request, post_id):
    """Редактирование поста. Доступно только автору."""

    template = "posts/create_post.html"

    post = get_object_or_404(Post, pk=post_id)

    # Если редактировать пытается не автор
    if request.user.id != post.author.id:
        return redirect("posts:post_detail", post.pk)

    if request.method == "POST":
        form = PostForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()

            user_name = request.user.username
            return redirect("posts:profile", user_name)

        return render(request, template, {"form": form})

    form = PostForm(instance=post)
    context = {
        "form": form,
        "is_edit": True,
    }
    return render(request, template, context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    """Собственная форма регистрации пользователя."""

    form_class = CreationForm
    success_url = reverse_lazy("posts:index")
    template_name = "users/signup.html"

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="container py-5">
    <h1>Привет, <span style="color:red">я</span> Павел.</h1>
    <p>Рад, что мой путь привел меня на <a href="https://practicum.yandex.ru" target="_blank">Yandex.Practicum</a>, где я разрабатываю данный проект.</p>
    <p>Мой <a href="https://github.com/web2cap" target="_blank">Github</a>, подписывайтесь!</p>
    <p>Практикум дает большую мотивацию в изучении разработки, я намерен дойти до конца и получить работу мечты.</p>
    <p><em>Полный вперед!</em></p>
</div>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
      <li class="list-group-item">
        Postgres
      </li>
      <li class="list-group-item">
        Bootstrap
      </li>
      <li class="list-group-item">
        HTML
      </li>
      <li class="list-group-item">
        CSS
      </li>
      <li class="list-group-item">
        Linux
      </li>
      <li class="list-group-item">
        Git
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Список технологий будет расширятся.</p>
    <p>В ближайшее свободное время научусть писать Telegram-бота и работать с OSM. </p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
  <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
  <meta name="msapplication-TileColor" content="#000">
  <meta name="theme-color" content="#ffffff">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>{% block title %}Yatube{% endblock %}</title>
</head>

<body>
  <header>
    {% include 'includes/header.html' %}
  </header>
  <main>
    {% block content%}
    {% endblock %}
  </main>
  <footer class="border-top text-center py-3">
    {% include 'includes/footer.html' %}
  </footer>
</body>

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:index' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" 
           class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>
    {% with request.resolver_match.view_name as view_name %}
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link{% if view_name  == 'about:author' %} active{% endif %}" 
           href="{% url 'about:author' %}">Об авторе</a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if view_name  == 'about:tech' %} active{% endif %}" 
           href="{% url 'about:tech' %}">Технологии</a>
      </li>
      {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link{% if view_name  == 'posts:post_create' %} active{% endif %}" 
             href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'password_change' %} active{% endif %}"
             href="{% url 'password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        <li>
      {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'users:login' %} active{% endif %}" 
             href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'users:signup' %} active{% endif %}"
             href="{% url 'users:signup' %}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
    {% endwith %}
  </div>
</nav>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}             
          </div>
          <div class="card-body">
              
            {% if form.errors %}
                {% for field in form %}
                {% for error in field.errors %}            
                    <div class="alert alert-danger">
                    {{ error|escape }}
                    </div>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
            {% endif %}

            <form method="post" action="{{ request.get_full_path }}">
              {% csrf_token %}
             
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}

              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %}
<div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
        {{ group.description }}
    </p>
    <article>
        {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        {% if not forloop.last %}
        <hr>{% endif %}
        {% endfor %}
    </article>

    {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
<div class="container py-5">
    {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
        </ul>
        <p>{{ post.text }}</p>
        <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a></p>
        {% if post.group %}
            <p><a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a></p>
        {% endif %}
        {% if not forloop.last %}
            <hr>
        {% endif %}
    {% endfor %}

    {% include 'posts/includes/paginator.html' %}


</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
          {% if post.group %}
              <li class="list-group-item">
                  Группа: {{ post.group.title }}
                  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              </li>
          {% endif %}
          <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>{{ post.text }}</p>
        {% if user.id ==  post.author.id %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
        {% endif %}
      </article>
  </div>
<div class="container py-5">
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Все посты пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
<div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    {% for post in page_obj %}
        <article>
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                    <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>{{ post.text }}</p>
            <p><a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a></p>
        </article> 
        {% if post.group %}
            <p><a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a></p>
        {% endif %}
        {% if not forloop.last %}
            <hr>
        {% endif %}
    {% endfor %}
    
    {% include 'posts/includes/paginator.html' %}
    
</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Выход
            </div>
            <div class="card-body">
                <p>
                    Вы вышли из своей учётной записи. Ждём вас снова!
                </p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
            </div>
            <div class="card-body">
                {% load user_filters %}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post" action="{% url 'users:password_reset' %}">
                    {% csrf_token %}
                    <div class="form-group row my-3 p-3">
                        <label for="id_email">
                            Адрес электронной почты
                            <span class="required text-danger">*</span>
                        </label>
                        <input type="email" name="email" maxlength="254" class="form-control" 
                               required id="id_email" value="{{ form.email.value|default:'' }}">
                    </div>
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Сбросить пароль
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Отправлено письмо
      </div>
      <div class="card-body">
        <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
      </div> 
    </div> 
  </div>
</div> 
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Cбросить старый пароль{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
            </div>
            <div class="card-body">
                {% load user_filters %}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                {% endif %}
                <form method="post" action="{% url 'users:password_reset' %}">
                    {% csrf_token %}
                    <div class="form-group row my-3 p-3">
                        <label for="id_email">
                            Адрес электронной почты
                            <span class="required text-danger">*</span>
                        </label>
                        <input type="email" name="email" maxlength="254" class="form-control" 
                               required id="id_email" value="{{ form.email.value|default:'' }}">
                    </div>
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                            Сбросить пароль
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>

                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}